import { NgModule } from "@angular/core";
import {
  MatButtonModule,
  MatCheckboxModule,
  MatDialogModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatPaginatorModule,
  MatSnackBarModule,
  MatSortModule,
  MatTableModule,
  MatTooltipModule,
  MatSelectModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatStepperModule,
  MatSlideToggleModule,
  MatListModule,
  DateAdapter,
  MAT_DATE_FORMATS,
  MatToolbarModule,
  MatMenuModule,
} from "@angular/material";
import {
  LMSDateAdapter,
  LMS_DATE_FORMATS,
} from "../inherited/lms-date.adapter";

@NgModule({
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatButtonModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatIconModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatStepperModule,
    MatSlideToggleModule,
    MatListModule,
    MatToolbarModule,
    MatMenuModule,
  ],
  exports: [
    MatTooltipModule,
    MatSnackBarModule,
    MatDialogModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatButtonModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatStepperModule,
    MatSlideToggleModule,
    MatListModule,
    MatToolbarModule,
    MatMenuModule,
  ],
  providers: [
    { provide: DateAdapter, useClass: LMSDateAdapter },
    { provide: MAT_DATE_FORMATS, useValue: LMS_DATE_FORMATS },
  ],
})
export class MaterialModule {}
